# Generated by Django 5.2.16 on 2026-07-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdes', models.CharField(help_text='NEOCP temporary designation (Kafka message key)', max_length=32)),
                ('last_run', models.DateTimeField(blank=True, help_text='Scout lastRun the event derives from', null=True)),
                ('event_type', models.CharField(choices=[('new_candidate', 'New candidate'), ('updated', 'Updated'), ('cancelled', 'Cancelled'), ('left_neocp', 'Left NEOCP')], max_length=16)),
                ('payload', models.JSONField(help_text='Full JSON message as published')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created', 'pk'],
                'unique_together': {('tdes', 'last_run', 'event_type')},
            },
        ),
    ]
